In [1]:
import numpy as np
import os

# Rename

In [5]:
import os
import re
def rename_pickles(directory,dry=True):
    if not os.path.exists(directory):
        print(f'dir {directory} not exist')
        return
    
    for filename in os.listdir(directory):
        if filename.endswith(".pickle"):
            new_filename = re.sub(r"_es\d+_", "_", filename)
            if new_filename != filename:
                if not dry:
                    os.rename(os.path.join(directory, filename), os.path.join(directory, new_filename))
                print(f"Renamed: {filename} -> {new_filename}")

In [10]:
rename_pickles('.',dry=True)

# Check missing and generate new params list

In [3]:
import numpy as np

In [4]:
with open('exist_1_3.txt','r') as f:
    zz=f.read().split('\n')

In [22]:
def generate_params(xj,L0,L1,seed_max,pctrl_list,pproj_list,anc=False,filename='params.txt',total=2000,exist=False,filelist=None):
    # xj='1-3,2-3'
    # pctrl_list=np.linspace(0,.6,21)
    # pproj_list=np.linspace(0,.6,21)
    es=total//seed_max
    fn_template='CT_En{es}_pctrl({pctrl:.2f},{pctrl:.2f},1)_pproj({pproj:.2f},{pproj:.2f},1)_L({L0},{L1},2)_xj({xj})_seed{seed}_64{anc}.pickle'
    params_text=[]
    for seed in range(seed_max):
        for pctrl in pctrl_list:
            for pproj in pproj_list:
                fn=fn_template.format(pctrl=pctrl,pproj=pproj,xj=xj.replace('/','-'),seed=seed,L0=L0,L1=L1,es=es,anc='_anc'*anc)
                if filelist is None:
                    file_exist = os.path.exists(fn)
                else:
                    with open(filelist,'r') as f:
                        fn_list=f.read().split('\n')
                    file_exist = fn in fn_list
                    
                if not file_exist:
                    params_text.append(f'{seed} {pctrl:.2f} {pproj:.2f} {L0:d} {L1:d} {xj:s} {es:d} {"-ancilla"*anc}')
                elif exist:
                    params_text.append(fn)

    
    if filename is not None:
        with open(filename,'a') as f:
            f.write('\n'.join(params_text)+'\n')

    return params_text

## Demo

In [23]:
params_text=generate_params(xj='0', L0=12, L1=14, seed_max=1, pctrl_list=np.linspace(0,.6,21),pproj_list=np.linspace(0,.6,21))

In [25]:
params_text=generate_params(xj='1-3,2-3', L0=12, L1=14, seed_max=1, pctrl_list=np.linspace(0,.6,21),pproj_list=np.linspace(0.27,.3,4))

In [29]:
params_text=generate_params(xj='0', L0=16, L1=18, seed_max=1, pctrl_list=np.linspace(0,.6,21),pproj_list=np.linspace(0,.6,21))

In [31]:
params_text=generate_params(xj='1-3,2-3', L0=16, L1=18, seed_max=1, pctrl_list=np.linspace(0,.6,21),pproj_list=np.linspace(0,.6,21))

In [16]:
params_text=generate_params(xj='0', L0=20, L1=22, seed_max=2, pctrl_list=np.linspace(0,.6,21),pproj_list=np.linspace(0,.6,21))

In [17]:
params_text=generate_params(xj='1/3,2/3', L0=20, L1=22, seed_max=2, pctrl_list=np.linspace(0,.6,21),pproj_list=np.linspace(0,.6,21))

## Generate no ancilla

In [6]:
for p_proj in [0,0.05,0.10,0.15,0.20]:
    params_text=generate_params(xj='0', L0=8, L1=10, seed_max=1, pctrl_list=np.linspace(0,.6,21),pproj_list=np.linspace(p_proj,p_proj,1),filename='params_small.txt',total=2000)
    params_text=generate_params(xj='0', L0=12, L1=14, seed_max=1, pctrl_list=np.linspace(0,.6,21),pproj_list=np.linspace(p_proj,p_proj,1),filename='params_small.txt',total=2000)
    params_text=generate_params(xj='0', L0=16, L1=18, seed_max=1, pctrl_list=np.linspace(0,.6,21),pproj_list=np.linspace(p_proj,p_proj,1),filename='params.txt',total=2000)
    params_text=generate_params(xj='0', L0=20, L1=22, seed_max=4, pctrl_list=np.linspace(0,.6,21),pproj_list=np.linspace(p_proj,p_proj,1),filename='params.txt',total=2000)
    params_text=generate_params(xj='0', L0=24, L1=26, seed_max=32, pctrl_list=np.linspace(0,.6,21),pproj_list=np.linspace(p_proj,p_proj,1),filename='params.txt',total=60*32)

In [ ]:
### xj={-1/3}

In [53]:
for p_proj in np.linspace(0,0.6,21):
    params_text=generate_params(xj='1/3,-1/3', L0=8, L1=10, seed_max=1, pctrl_list=np.linspace(0,.6,21),pproj_list=np.linspace(p_proj,p_proj,1),filename='params_m1_3.txt',total=2000,filelist=None)
    params_text=generate_params(xj='1/3,-1/3', L0=12, L1=14, seed_max=1, pctrl_list=np.linspace(0,.6,21),pproj_list=np.linspace(p_proj,p_proj,1),filename='params_m1_3.txt',total=2000,filelist=None)
    params_text=generate_params(xj='1/3,-1/3', L0=16, L1=18, seed_max=1, pctrl_list=np.linspace(0,.6,21),pproj_list=np.linspace(p_proj,p_proj,1),filename='params_m1_3.txt',total=2000,filelist=None)
    params_text=generate_params(xj='1/3,-1/3', L0=20, L1=22, seed_max=2, pctrl_list=np.linspace(0,.6,21),pproj_list=np.linspace(p_proj,p_proj,1),filename='params_m1_3.txt',total=2000,filelist=None)
    # params_text=generate_params(xj='1/3,-1/3', L0=24, L1=26, seed_max=32, pctrl_list=np.linspace(0,.6,21),pproj_list=np.linspace(p_proj,p_proj,1),filename='params_m1_3.txt',total=60*32)

In [16]:
32*60

1920

In [66]:
for p_proj in np.arange(0,0.6,0.03):
    # pctrl_list=pctrl_list_list[p_proj]
    # pctrl_list=np.round(np.arange(0.45,.56,0.01),2)
    pctrl_list=np.round(np.arange(0,0.6,0.03),2)

    params_text=generate_params(xj='1/3,2/3', L0=8, L1=10, seed_max=1, pctrl_list=pctrl_list,pproj_list=np.linspace(p_proj,p_proj,1),filename='params.txt',total=2000,filelist='exist_1_3.txt')
    params_text=generate_params(xj='1/3,2/3', L0=12, L1=14, seed_max=1, pctrl_list=pctrl_list,pproj_list=np.linspace(p_proj,p_proj,1),filename='params.txt',total=2000,filelist='exist_1_3.txt')
    params_text=generate_params(xj='1/3,2/3', L0=16, L1=18, seed_max=1, pctrl_list=pctrl_list,pproj_list=np.linspace(p_proj,p_proj,1),filename='params.txt',total=2000,filelist='exist_1_3.txt')
    params_text=generate_params(xj='1/3,2/3', L0=20, L1=22, seed_max=2, pctrl_list=pctrl_list,pproj_list=np.linspace(p_proj,p_proj,1),filename='params.txt',total=2000,filelist='exist_1_3.txt')
    #params_text=generate_params(xj='1/3,2/3', L0=24, L1=26, seed_max=32, pctrl_list=pctrl_list,pproj_list=np.linspace(p_proj,p_proj,1),filename='params.txt',total=60*32)

In [52]:
14*142

1988

## Generate ancilla

### xj={0}

In [11]:
#0
np.linspace(0.29,0.37,9)
np.linspace(0.47,0.5,4)

array([0.47, 0.48, 0.49, 0.5 ])

In [16]:
#0.05
# np.linspace(0.24,0.3,7)
# np.linspace(.48,.51,4)

array([0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ])

In [20]:
#0.10
np.linspace(.15,.23,9)
np.linspace(.44,.54,11)

array([0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54])

In [22]:
#0.15
np.linspace(.07,.12, 6)
np.linspace(.47,.52, 6)

array([0.47, 0.48, 0.49, 0.5 , 0.51, 0.52])

In [24]:
#0.2
np.linspace(.0,.05, 6)
np.linspace(.47,.52, 6)

array([0.47, 0.48, 0.49, 0.5 , 0.51, 0.52])

In [33]:
# 0.03
np.linspace(.27,.33,7)
# 0.06
np.linspace(.23,.29,7)
# 0.09
np.linspace(.17,.23,7)
# 0.12
np.linspace(.12,.18,7)
# 0.18
np.linspace(.01,.07,7)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07])

In [1]:
0.33,0
0.28,0.05

(0.33, 0)

In [6]:
def linfit(a,b,x):
    return (x-a[0])*(b[1]-a[1])/(b[0]-a[0])+a[1]


In [32]:
linfit([0.2,0.0],[0.15,0.09],0.18)

0.03600000000000002

### xj={-1/3}

In [42]:
pctrl_list_list={
    0.:np.r_[np.arange(0.20,0.26,0.01),np.arange(0.48,0.53,0.01)],
    0.03:np.r_[np.arange(0.16,0.22,0.01),np.arange(0.48,0.53,0.01)],
    0.06:np.r_[np.arange(0.15,0.21,0.01),np.arange(0.48,0.53,0.01)],
    0.09:np.r_[np.arange(0.13,0.20,0.01),np.arange(0.48,0.53,0.01)],
    0.12:np.r_[np.arange(0.09,0.15,0.01),np.arange(0.48,0.53,0.01)],
    0.15:np.r_[np.arange(0.05,0.10,0.01),np.arange(0.48,0.53,0.01)],
    0.18:np.r_[np.arange(0.0,0.05,0.01),np.arange(0.48,0.53,0.01)],
    0.21:np.r_[np.arange(0.0,0.05,0.01),np.arange(0.48,0.53,0.01)],
    }
    

In [73]:
# p_proj=0.24
# pctrl_list=np.round(np.linspace(0,.6,21),2)
pctrl_list=np.round(np.arange(0.45,.56,0.01),2)
# for p_proj in np.arange(0,0.22,0.03):
for p_proj in np.arange(0.00,0.37,0.03):
    # pctrl_list=pctrl_list_list[p_proj]

# pctrl_list=np.union1d(pctrl_list, np.round(np.linspace(.47,.52, 6),2))
# filelist='exist_1_3.txt'

    params_text=generate_params(xj='1/3,2/3', L0=8, L1=10, seed_max=5, pctrl_list=pctrl_list,pproj_list=np.linspace(p_proj,p_proj,1),anc=True,filename='params.txt',total=10000,filelist='exist_1_3.txt')

    params_text=generate_params(xj='1/3,2/3', L0=10, L1=12, seed_max=5, pctrl_list=pctrl_list,pproj_list=np.linspace(p_proj,p_proj,1),anc=True,filename='params.txt',total=10000,filelist='exist_1_3.txt')

    params_text=generate_params(xj='1/3,2/3', L0=12, L1=14, seed_max=5, pctrl_list=pctrl_list,pproj_list=np.linspace(p_proj,p_proj,1),anc=True,filename='params.txt',total=10000,filelist='exist_1_3.txt')

    params_text=generate_params(xj='1/3,2/3', L0=14, L1=16, seed_max=5, pctrl_list=pctrl_list,pproj_list=np.linspace(p_proj,p_proj,1),anc=True,filename='params.txt',total=10000,filelist='exist_1_3.txt')

    params_text=generate_params(xj='1/3,2/3', L0=14, L1=16, seed_max=5, pctrl_list=pctrl_list,pproj_list=np.linspace(p_proj,p_proj,1),anc=True,filename='params.txt',total=10000,filelist='exist_1_3.txt')

    params_text=generate_params(xj='1/3,2/3', L0=16, L1=18, seed_max=5, pctrl_list=pctrl_list,pproj_list=np.linspace(p_proj,p_proj,1),anc=True,filename='params.txt',total=10000,filelist='exist_1_3.txt')

    params_text=generate_params(xj='1/3,2/3', L0=18, L1=20, seed_max=5, pctrl_list=pctrl_list,pproj_list=np.linspace(p_proj,p_proj,1),anc=True,filename='params.txt',total=10000,filelist='exist_1_3.txt')

    params_text=generate_params(xj='1/3,2/3', L0=20, L1=22, seed_max=20, pctrl_list=pctrl_list,pproj_list=np.linspace(p_proj,p_proj,1),anc=True,filename='params.txt',total=10000,filelist='exist_1_3.txt')

# params_text=generate_params(xj='1/3,2/3', L0=22, L1=24, seed_max=100, pctrl_list=pctrl_list,pproj_list=np.linspace(p_proj,p_proj,1),anc=True,filename='params.txt',total=10000,filelist='exist_1_3.txt')

# XEB

In [14]:
def generate_params_XEB(xj,L0,L1,seed_m_max,seed_C_max,pctrl_list,pproj_list,anc=False,filename='params.txt',total=4000,total_C=1280,exist=False,filelist=None):
    es_m=total//seed_m_max
    es_C=total_C//seed_C_max
    fn_template='CT_En{es_C}_Enm{es_m}_pctrl({pctrl:.2f},{pctrl:.2f},1)_pproj({pproj:.2f},{pproj:.2f},1)_L({L0},{L1},2)_xj({xj})_seed{seed}_seedC{seed_C}_64{anc}_XEB_Haar_encoding.pickle'
    params_text=[]
    for seed in range(seed_m_max):
        for seed_C in range(seed_C_max):
            for pctrl in pctrl_list:
                for pproj in pproj_list:
                    fn=fn_template.format(pctrl=pctrl,pproj=pproj,xj=xj.replace('/','-'),seed=seed,seed_C=seed_C,L0=L0,L1=L1,es_m=es_m,es_C=es_C,anc='_anc'*anc)
                    if filelist is None:
                        file_exist = os.path.exists(fn)
                    else:
                        with open(filelist,'r') as f:
                            fn_list=f.read().split('\n')
                        file_exist = fn in fn_list
                        
                    if not file_exist:
                        params_text.append(f'{seed} {seed_C} {pctrl:.2f} {pproj:.2f} {L0:d} {L1:d} {xj:s} {es_m:d} {es_C:d}{"-ancilla"*anc}')
                    elif exist:
                        params_text.append(fn)
    
    if filename is not None:
        with open(filename,'a') as f:
            f.write('\n'.join(params_text)+'\n')

    return params_text

In [15]:
for p_proj in np.linspace(0,0.0,1):
    params_text=generate_params_XEB(xj='0', L0=8, L1=10, seed_m_max=1,seed_C_max=1, pctrl_list=np.arange(0.26,0.35,0.01),pproj_list=np.linspace(p_proj,p_proj,1),filename='params_XEB.txt',total=4000,total_C=1280,filelist=None)
    # params_text=generate_params_XEB(xj='0', L0=12, L1=14, seed_m_max=1, pctrl_list=np.arange(0.26,0.35,0.01),pproj_list=np.linspace(p_proj,p_proj,1),filename='params_XEB.txt',total=2000,filelist=None)
    # params_text=generate_params_XEB(xj='0', L0=16, L1=18, seed_m_max=1, pctrl_list=np.arange(0.26,0.35,0.01),pproj_list=np.linspace(p_proj,p_proj,1),filename='params_XEB.txt',total=2000,filelist=None)
    # params_text=generate_params_XEB(xj='0', L0=20, L1=22, seed_m_max=2, pctrl_list=np.arange(0.26,0.35,0.01),pproj_list=np.linspace(p_proj,p_proj,1),filename='params_XEB.txt',total=2000,filelist=None)
    # params_text=generate_params_XEB(xj='0', L0=24, L1=26, seed_m_max=32, pctrl_list=np.arange(0.26,0.35,0.01),pproj_list=np.linspace(p_proj,p_proj,1),filename='params_XEB.txt',total=60*32)

# Legacy

In [75]:
with open('run_pytorch_sweep_params_20.txt','w') as f:
    f.write("\n".join(params_text))

In [8]:
params_text=[]
for seed in range(25):
    for idx in np.linspace(0,1,11):
        params_text.append(f'{seed} {idx:.1f}')

In [ ]:
with open('job_values.txt','w') as f:
    f.write("\n".join(params_text))

In [3]:
import re

# Looping over the range 0 to 110
def check_int(jobid,jobnum):
    error_list=[]
    missing_list=[]
    success_list=[]
    # for i in range(25*11):
    for i in range(jobnum):
        file_name = f"{jobid}.{i}.error"
        try:
            with open(file_name, 'r') as f:
                content = f.read()
                # Check if the word "Error" exists in the content
                if "Error" in content:
                    error_list.append(i)
                else:
                    success_list.append(i)
        except FileNotFoundError:
            missing_list.append(i)
    return success_list, error_list,missing_list

# Looping over the range 0 to 110
def check_int_output(jobid,jobnum):
    error_list=[]
    missing_list=[]
    success_list=[]
    # for i in range(25*11):
    for i in range(jobnum):
        file_name = f"{jobid}.{i}.output"
        try:
            with open(file_name, 'r') as f:
                content = f.read()
                # Check if the word "Error" exists in the content
                if "elapsed" in content:
                    success_list.append(i)
                else:
                    error_list.append(i)
        except FileNotFoundError:
            missing_list.append(i)
    return success_list, error_list,missing_list

In [18]:
success_list,error_list,missing_list=check_int(290130, 1100)

In [19]:
len(success_list)

557

In [20]:
len(error_list)

155

In [21]:
len(missing_list)

388

### 8

In [38]:
success_list,error_list,missing_list=check_int(290163, 110)

In [39]:
len(success_list),len(error_list),len(missing_list)

(1, 0, 109)

In [37]:
generate_next('run_pytorch_sweep_params_8.txt',error_list)

### 10-14

In [ ]:
success_list,error_list,missing_list=check_int(290160, 110)

In [ ]:
len(success_list),len(error_list),len(missing_list)

(3, 7, 100)

In [ ]:
success_list

[0, 1, 4]

In [ ]:
generate_next('run_pytorch_sweep_params_10-14.txt',error_list)

### 12

In [12]:
success_list,error_list,missing_list=check_int_output(290218, 1)

In [13]:
len(success_list),len(error_list),len(missing_list)

(1, 0, 0)

In [11]:
generate_next('run_pytorch_sweep_params_12.txt',error_list)

### 16

In [9]:
success_list,error_list,missing_list=check_int_output(290190, 42)

In [10]:
len(success_list),len(error_list),len(missing_list)

(42, 0, 0)

In [11]:
error_list

[]

In [ ]:
generate_next('run_pytorch_sweep_params_16.txt',error_list)

### 18

In [51]:
success_list,error_list,missing_list=check_int(290159, 30)

In [52]:
len(success_list),len(error_list),len(missing_list)

(4, 0, 26)

In [53]:
generate_next('run_pytorch_sweep_params_18.txt',error_list)

### 20

In [9]:
# success_list,error_list,missing_list=check_int(290203, 37)
success_list,error_list,missing_list=check_int_output(290219, 7)
# success_list,error_list,missing_list=check_int_output(290217, 882)

In [10]:
len(success_list),len(error_list),len(missing_list)

(7, 0, 0)

In [8]:
generate_next('run_pytorch_sweep_params_20_0.txt',error_list+missing_list)

In [7]:
def generate_next(original,redolist):

    with open(original,'r') as f:
        params=f.read().split('\n')
    error_txt='\n'.join([params[idx] for idx in redolist])
    with open(original,'w') as f:
        f.write(error_txt)

In [23]:
2**20*8*2000/1024**3*21**2

6890.625

In [15]:
2**26*8*2000/1024**3

1000.0